name: Client CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run unit tests
      run: npm test -- --run

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Run E2E tests
      run: npm run test:e2e

    - name: Build production bundle
      run: npm run build

    - name: Run Lighthouse audit
      # This step is optional and requires a server to be running.
      # You can use a package like `start-server-and-test`.
      # For simplicity, this is commented out.
      # run: |
      #   npm install -g @lhci/cli
      #   lhci autorun
      continue-on-error: true

  deploy:
    needs: test-and-build
    if: startsWith(github.ref, 'refs/tags/release/')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Build production bundle
      run: npm run build

    - name: Package handoff artifact
      run: zip -r handoff.zip dist/ assets/ public/ src/ components/ tokens/ provably_fair.md README.md

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: handoff-package
        path: handoff.zip
